#!/usr/bin/env python3
"""Paper Fig. 1: make the TopoNav contribution boundary explicit."""
from pathlib import Path
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch, Rectangle

ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'paper_assets/figures/toponav_method_and_contribution.png'
fig,ax=plt.subplots(figsize=(15,7.2));ax.set_xlim(0,15);ax.set_ylim(0,8);ax.axis('off');fig.patch.set_facecolor('white')
def box(x,y,w,h,title,lines,color='#64748b',fill='#f8fafc',lw=1.8):
 ax.add_patch(FancyBboxPatch((x,y),w,h,boxstyle='round,pad=.03,rounding_size=.12',fc=fill,ec=color,lw=lw))
 ax.text(x+.16,y+h-.32,title,fontsize=12,weight='bold',color='#172033',va='top')
 for i,s in enumerate(lines):ax.text(x+.16,y+h-.72-.34*i,s,fontsize=9.2,color='#4a586d',va='top')
def arrow(x1,y1,x2,y2,color='#64748b',style='-'):
 ax.add_patch(FancyArrowPatch((x1,y1),(x2,y2),arrowstyle='-|>',mutation_scale=13,lw=1.8,color=color,linestyle=style))
ax.text(.25,7.6,'TopoNav Harness: where the contribution enters the robot navigation stack',fontsize=20,weight='bold',color='#111827')
ax.text(.25,7.15,'Frozen VLM provides semantic choice; our harness makes that choice topology-grounded, validatable and execution-aware.',fontsize=11.5,color='#536176')
# Off-the-shelf inputs
box(.3,4.45,2.1,1.85,'Task + RGB',['“Enter room B through','the main portal”','current camera view'])
box(.3,2.15,2.1,1.85,'Semantic topology',['typed areas / portals','known connectivity','no metric path to VLM'])
# Ours boundary
ax.add_patch(FancyBboxPatch((2.75,1.05),9.4,5.55,boxstyle='round,pad=.08,rounding_size=.18',fc='#ecfdf5',ec='#12936a',lw=2.5,linestyle='--'))
ax.text(2.98,6.32,'OUR ROBOT-FACING HARNESS',fontsize=11,weight='bold',color='#087a55')
box(3.05,4.05,2.35,1.8,'1  Context compiler',['task-relevant subgraph','≤2 selected images','fixed token budget'],'#12936a','#ffffff',2.2)
box(5.75,4.05,2.15,1.8,'2  Frozen VLM',['semantic reasoning only','JSON named tool call','NAVIGATE(portal_03)'],'#4f76b6','#ffffff',1.8)
box(8.25,4.05,2.25,1.8,'3  Tool validator',['exists / adjacent?','relation precondition?','STOP actually verified?'],'#12936a','#ffffff',2.2)
box(10.85,4.05,1.0,1.8,'4',['allow','or','reject'],'#12936a','#ffffff',2.2)
box(3.05,1.4,2.35,1.8,'7  Relation memory',['preserve task intent','remember failed edge','compile next context'],'#12936a','#ffffff',2.2)
box(6.0,1.4,2.35,1.8,'6  Typed feedback',['SUCCESS / INVALID','NO_PROGRESS / TIMEOUT','distance + relation state'],'#12936a','#ffffff',2.2)
box(9.0,1.4,2.35,1.8,'5  Metric executor',['symbolic edge → pose','Habitat-GS / Nav2','fixed low-level planner'],'#64748b','#ffffff',1.8)
# arrows
arrow(2.4,5.35,3.05,5.05);arrow(2.4,3.2,3.05,4.65);arrow(5.4,5.05,5.75,5.05);arrow(7.9,5.05,8.25,5.05);arrow(10.5,5.05,10.85,5.05);arrow(11.35,4.25,10.2,3.2);arrow(9.0,2.42,8.35,2.42);arrow(6.0,2.42,5.4,2.42);arrow(4.2,3.2,4.2,4.25,'#12936a','--')
# downstream and callout
box(12.55,3.65,2.05,2.05,'Physical execution',['RGB + NavMesh trace','goal reached / failed','robot motion is not','generated by the VLM'],'#64748b','#f8fafc')
arrow(11.85,5.05,12.55,4.75)
ax.add_patch(Rectangle((.3,.25),14.3,.55,fc='#172033',ec='none'))
ax.text(.55,.525,'Observed on the same 80 tasks:  Direct-VLM 10.0%  →  Full-history 57.5%  →  TopoNav Harness 73.8% SR',fontsize=12,weight='bold',color='white',va='center')
ax.text(12.55,2.95,'Gray/blue = reused',fontsize=10,color='#536176',weight='bold');ax.text(12.55,2.58,'Green = our contribution',fontsize=10,color='#087a55',weight='bold')
OUT.parent.mkdir(parents=True,exist_ok=True);fig.savefig(OUT,dpi=240,bbox_inches='tight');plt.close(fig);print(OUT)
